name: CI Workflow

on:
  push:
    branches:
      - main

env:
  DOCKER_HOST: tcp://localhost:2375   # Fix: Point to localhost
  DOCKER_TLS_CERTDIR: ""              # Disable TLS
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    container:
      image: maverick96k/maven-akshay-docker-agent:v2
    defaults:
      run:
        working-directory: java-maven-sonar-argocd-helm-k8s/spring-boot-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile the code
        run: |
          echo "Compiling the code..."
          mvn clean package

  test:
    name: Unit Test Job
    runs-on: ubuntu-latest
    container:
      image: maverick96k/maven-akshay-docker-agent:v2
    defaults:
      run:
        working-directory: java-maven-sonar-argocd-helm-k8s/spring-boot-app
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          echo "Running unit tests... This will take about 60 seconds."
          mvn test

  sonarqube:
    name: Code Quality (SonarQube)
    runs-on: ubuntu-latest
    container:
      image: maverick96k/maven-akshay-docker-agent:v2
    defaults:
      run:
        working-directory: java-maven-sonar-argocd-helm-k8s/spring-boot-app
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        run: |
          echo "Scanning code..."
          mvn sonar:sonar -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_LOGIN}

  dockerization:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: sonarqube
    services:
      docker:
        image: docker:19.03-dind
        options: --privileged
        ports:
          - 2375:2375   # Expose Docker daemon on port 2375
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          whoami
          docker build -t githubactions-cicd-demo:latest .
          docker tag githubactions-cicd-demo:latest ${{ secrets.DOCKER_USERNAME }}/githubactions-cicd-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/githubactions-cicd-demo:latest
